### ISSUE TITLE
Listing stored authorizations doesn't work in v.1.0.0

### ISSUE THREAD

**Issue by 0dysseas** [canonical/surl#46]
Issuing `surl -l` doesn't work and errors out with:

```
no1@metis:$ surl -l
Available credentials:
Traceback (most recent call last):
  File "/snap/surl/424/bin/surl_cli.py", line 28, in <module>
    sys.exit(main())
  File "/snap/surl/424/lib/python3.8/site-packages/surl/__init__.py", line 430, in main
    url, config, remainder = get_config_from_cli(parser, auth_dir)
  File "/snap/surl/424/lib/python3.8/site-packages/surl/__init__.py", line 248, in get_config_from_cli
    for ident, store_env in list_configs(auth_dir):
  File "/snap/surl/424/lib/python3.8/site-packages/surl/__init__.py", line 162, in list_configs
    config = load_config(os.path.join(path, f))
  File "/snap/surl/424/lib/python3.8/site-packages/surl/__init__.py", line 134, in load_config
    a["type"],
KeyError: 'type'
```
The installed version is `1.0.0`:

```
no1@metis:$ snap info surl
name:      surl
summary:   Ubuntu Store API thin wrapper.
publisher: Daniel Manrique (tomechangosubanana)
store-url: https://snapcraft.io/surl
license:   unset
description: |
  Ubuntu Store API thin wrapper.
commands:
  - surl.metrics
  - surl.monthinsnaps
  - surl.storeops
  - surl
snap-id:      LpV8761EjlAPqeXxfYhQvpSWgpxvEWpN
tracking:     latest/edge
refresh-date: 6 days ago, at 16:27 EET
channels:
  latest/stable:    0.8.0 2021-10-26 (414)  7MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      1.0.0 2022-12-01 (424) 25MB -
installed:          1.0.0            (424) 25MB -
```

**Comment by 0dysseas** [comment]
I think I found the problem. Some of the credentials that were already stored on my machine (in `/snap/surl/common`), do not contain the `"type"` key. Looking a bit into the [commit](https://github.com/canonical/surl/commit/b8108a9ba7713b422503509389426e9b533111b0) that introduced this change, it seems this was done as a way to differentiate between the 2 different authentication back-ends (i.e. sca & charmhub).

If this is the case, would a trivial change to `a.get("type", "snapcraft")` suffice or do you think there's other behavior that also needs to be modified? I've tested this locally and works OK but as I'm not familiar with `surl`, was wondering if I'm missing something?

**Comment by shanepelletier** [comment]
Totally forgot to close this, fixed in https://github.com/canonical/surl/commit/2387e151e148b8698b63834b338c02bf9ebea420.
